AWSTemplateFormatVersion: '2010-09-09'
Description: 'Partition Key y Sort Key'

Resources:
  TablaUsuariosConGSI:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "UsuariosSeguridad"
      AttributeDefinitions:
        - AttributeName: "UserId"
          AttributeType: "S"
        - AttributeName: "Email"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "UserId"
          KeyType: "HASH"
      BillingMode: PAY_PER_REQUEST
      # Definición del Índice
      GlobalSecondaryIndexes:
        - IndexName: "EmailIndex"
          KeySchema:
            - AttributeName: "Email"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL" # Copia todos los atributos al índice


Outputs:
  TableName:
    Description: "Nombre de la tabla creada"
    Value: !Ref TablaUsuariosConGSI