AWSTemplateFormatVersion: '2010-09-09'
Description: 'Partition Key y Sort Key'

Resources:
  TablaSesionesSegura:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "SesionesApp"
      AttributeDefinitions:
        - AttributeName: "SessionId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "SessionId"
          KeyType: "HASH"
      BillingMode: PAY_PER_REQUEST
      # 1. ACTIVAR EL TTL (Auto-borrado)
      TimeToLiveSpecification:
        AttributeName: "ExpiraEn" # Nombre del campo con la fecha
        Enabled: true
      # 2. ACTIVAR LA MÁQUINA DEL TIEMPO (PITR)
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true


Outputs:
  TableName:
    Description: "Nombre de la tabla creada"
    Value: !Ref TablaSesionesSegura